### ISSUE TITLE
japanese dating site

### ISSUE THREAD

**Issue by rwkaye** [lvtk/lvtk#24]
The web link http://lvtoolkit.org takes me to a Japanese Dating site.  Are you serious or is this a scam?

I'm not impressed...

**Comment by trebmuh** [comment]
(curiosity here) How do you know it's a dating website ? I'm only seeing a crocodile (kind of) muppet.

**Comment by rwkaye** [comment]
well, google translate tells me it's japanese and translates the title as "How to shoot matchmaking photos".  I didn't look any further, so maybe I jumped to the wrong conclusion. But I was only looking for documentation on LV2 stuff and didn't see any, and that's the real point...

**Comment by mfisher31** [comment]
oh wow.  I don't actually own that domain any more... updating links immediately.

**Comment by trebmuh** [comment]
@rwkaye makes sense
