### ISSUE TITLE
2.0.0-rc1 doesn't install lvtk-plugin-2 and beatslash fails to compile

### ISSUE THREAD

**Issue by yurivict** [lvtk/lvtk#45]
Log: http://beefy6.nyi.freebsd.org/data/121amd64-default/550235/logs/errors/beatslash-lv2-1.0.6_2.log
Beatslash LV2: https://github.com/blablack/beatslash-lv2

Do you know what is wrong? Why 2.0.0-rc1 doesn't install lvtk-plugin-2 any more?

**Comment by mfisher31** [comment]
The static libraries were removed for 2.x.x, and LVTK is now a header only library.  change `lvtk-plugin-2` to `lvtk-2` and the configure should work.

**Comment by yurivict** [comment]
After I made this change configure passes but the build fails:
```
../src/beatrepeater_stereo.cpp:14:7: error: no matching constructor for initialization of 'Plugin<BeatRepeaterStereo>'
    : Plugin<BeatRepeaterStereo>(p_n_ports)
      ^                          ~~~~~~~~~
../../../../../../local/include/lvtk-2/lvtk/plugin.hpp:177:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'p_port_enum' to 'const lvtk::Plugin<BeatRepeaterStereo>' for 1st argument
class Plugin : public E<S>...
      ^
../../../../../../local/include/lvtk-2/lvtk/plugin.hpp:188:14: note: candidate constructor not viable: no known conversion from 'p_port_enum' to 'const lvtk::Args' for 1st argument
    explicit Plugin (const Args& args) : E<S> (args.features)... {}
             ^
../../../../../../local/include/lvtk-2/lvtk/plugin.hpp:181:5: note: candidate constructor not viable: requires 0 arguments, but 1 was provided
    Plugin() = delete;
    ^
../src/beatrepeater_stereo.cpp:44:22: error: use of undeclared identifier 'p'
    int tempo = int(*p(p_tempo) + 0.5);
                     ^
```

This began to fail after the ```lvtk``` update. Maybe there's an easy patch to fix this?

(I am a port maintainer and am trying to figure out build failures.)

**Comment by mfisher31** [comment]
The API was re-written in 2.x, and is causing those errors.  Looks like the BeatRepeater author will need to update the plugin to support 2.0.  They could also include LVTK directly in their code-base instead of relying on system install of LVTK.

**Comment by yurivict** [comment]
I've let the author know.

Thank you for your help!

**Comment by mfisher31** [comment]
No problem @yurivict !
