### ISSUE TITLE
Build fails on Debian testing

### ISSUE THREAD

**Issue by grammoboy2** [lvtk/lvtk#46]
lvtk$ ./waf
Waf: Entering directory `/home/debian/myhome/develop/lvtk/build'
[1/4] Compiling plugins/volume.cpp
In file included from ../plugins/volume.cpp:3:
/home/debian/myhome/develop/lvtk/lvtk/plugin.hpp:258:57: error: using typedef-name ‘LV2_Descriptor’ after ‘struct’
  258 |     inline static LV2_Handle _instantiate (const struct LV2_Descriptor*  descriptor,
      |                                                         ^~~~~~~~~~~~~~
In file included from /home/debian/myhome/develop/lvtk/lvtk/lvtk.hpp:48,
                 from /home/debian/myhome/develop/lvtk/lvtk/plugin.hpp:33,
                 from ../plugins/volume.cpp:3:
/usr/lib/lv2/core.lv2/lv2.h:343:3: note: ‘LV2_Descriptor’ has a previous declaration here
  343 | } LV2_Descriptor;
      |   ^~~~~~~~~~~~~~
In file included from ../plugins/volume.cpp:3:
/home/debian/myhome/develop/lvtk/lvtk/plugin.hpp: In instantiation of ‘void lvtk::Descriptor<P>::register_plugin(const char*) [with P = Volume]’:
/home/debian/myhome/develop/lvtk/lvtk/plugin.hpp:85:9:   required from ‘lvtk::Descriptor<P>::Descriptor(const char*) [with P = Volume]’
../plugins/volume.cpp:67:62:   required from here
/home/debian/myhome/develop/lvtk/lvtk/plugin.hpp:94:29: error: invalid conversion from ‘void* (*)(const int*, double, const char*, const LV2_Feature* const*)’ to ‘void* (*)(const _LV2_Descriptor*, double, const char*, const LV2_Feature* const*)’ [-fpermissive]
   94 |         desc.instantiate    = P::_instantiate;
      |         ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
      |                             |
      |                             void* (*)(const int*, double, const char*, const LV2_Feature* const*)

Waf: Leaving directory `/home/debian/myhome/develop/lvtk/build'
Build failed
 -> task in 'volume' failed with exit status 1 (run with -v to display more information)

**Comment by mfisher31** [comment]
Fixed in `master` @grammoboy2 . thanks for the report.

**Comment by grammoboy2** [comment]
Thx, fixed. (But apparently   https://github.com/moddevices/mod-ams-lv2 needs lvtk-plugin-1, hmm)
