### ISSUE TITLE
build lvtk-1

### ISSUE THREAD

**Issue by grammoboy2** [lvtk/lvtk#47]
Sorry, I need lvtk-1 and need some help to build it

https://github.com/moddevices/mod-ams-lv2/issues/15

Do I need to checkout another git branch?

$ git branch -a
* master
  remotes/origin/1.x
  remotes/origin/HEAD -> origin/master
  remotes/origin/feature/nk
  remotes/origin/master
  remotes/origin/travis-ci

 git checkout 1.x
Branch '1.x' set up to track remote branch '1.x' from 'origin'.
Switched to a new branch '1.x'

$ ./waf configure
Waf: The wscript in '/home/debian/myhome/develop/lvtk' is unreadable
Traceback (most recent call last):
  File "/home/debian/myhome/develop/lvtk/.waf3-1.7.2-89df5661dd0948598701ec3b9c0a4216/waflib/Scripting.py", line 87, in waf_entry_point
    set_main_module(Context.run_dir+os.sep+Context.WSCRIPT_FILE)
  File "/home/debian/myhome/develop/lvtk/.waf3-1.7.2-89df5661dd0948598701ec3b9c0a4216/waflib/Scripting.py", line 112, in set_main_module
    Context.g_module=Context.load_module(file_path)
  File "/home/debian/myhome/develop/lvtk/.waf3-1.7.2-89df5661dd0948598701ec3b9c0a4216/waflib/Context.py", line 281, in load_module
    exec(compile(code,path,'exec'),module.__dict__)
  File "/home/debian/myhome/develop/lvtk/wscript", line 158
    if tag : print "Git Tag Created: " + tag
                   ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Git Tag Created: " + tag)?

**Comment by mfisher31** [comment]
That looks like it'd fix it.  I updated the 1.x branch with the change.

**Comment by grammoboy2** [comment]
$ ./waf configure

Traceback (most recent call last):
   File 
"/home/debian/myhome/develop/lvtk/.waf3-1.7.2-89df5661dd0948598701ec3b9c0a4216/waflib/Node.py", 
line 281, in ant_iter
     raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
   File 
"/home/debian/myhome/develop/lvtk/.waf3-1.7.2-89df5661dd0948598701ec3b9c0a4216/waflib/Scripting.py", 
line 97, in waf_entry_point
     run_commands()
   File 
"/home/debian/myhome/develop/lvtk/.waf3-1.7.2-89df5661dd0948598701ec3b9c0a4216/waflib/Scripting.py", 
line 149, in run_commands
     parse_options()
   File 
"/home/debian/myhome/develop/lvtk/.waf3-1.7.2-89df5661dd0948598701ec3b9c0a4216/waflib/Scripting.py", 
line 127, in parse_options
     Context.create_context('options').execute()
   File 
"/home/debian/myhome/develop/lvtk/.waf3-1.7.2-89df5661dd0948598701ec3b9c0a4216/waflib/Options.py", 
line 134, in execute
     super(OptionsContext,self).execute()
   File 
"/home/debian/myhome/develop/lvtk/.waf3-1.7.2-89df5661dd0948598701ec3b9c0a4216/waflib/Context.py", 
line 87, in execute
     self.recurse([os.path.dirname(g_module.root_path)])
   File 
"/home/debian/myhome/develop/lvtk/.waf3-1.7.2-89df5661dd0948598701ec3b9c0a4216/waflib/Context.py", 
line 128, in recurse
     user_function(self)
   File "/home/debian/myhome/develop/lvtk/wscript", line 41, in options
     opts.load("cross compiler_c compiler_cxx lv2 boost")
   File 
"/home/debian/myhome/develop/lvtk/.waf3-1.7.2-89df5661dd0948598701ec3b9c0a4216/waflib/Context.py", 
line 84, in load
     fun(self)
   File 
"/home/debian/myhome/develop/lvtk/.waf3-1.7.2-89df5661dd0948598701ec3b9c0a4216/waflib/Tools/compiler_c.py", 
line 31, in options
     opt.load_special_tools('c_*.py',ban=['c_dumbpreproc.py'])
   File 
"/home/debian/myhome/develop/lvtk/.waf3-1.7.2-89df5661dd0948598701ec3b9c0a4216/waflib/Context.py", 
line 264, in load_special_tools
lst=self.root.find_node(waf_dir).find_node('waflib/extras').ant_glob(var)
   File 
"/home/debian/myhome/develop/lvtk/.waf3-1.7.2-89df5661dd0948598701ec3b9c0a4216/waflib/Node.py", 
line 330, in ant_glob
     ret=[x for x in 
self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=25,dir=dir,src=src,remove=kw.get('remove',True))]
   File 
"/home/debian/myhome/develop/lvtk/.waf3-1.7.2-89df5661dd0948598701ec3b9c0a4216/waflib/Node.py", 
line 330, in <listcomp>
     ret=[x for x in 
self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=25,dir=dir,src=src,remove=kw.get('remove',True))]
RuntimeError: generator raised StopIteration

**Comment by grammoboy2** [comment]
So unfortunately still a problem here it seems.
