### ISSUE TITLE
GTK2 is EOL

### ISSUE THREAD

**Issue by dvzrv** [lvtk/lvtk#48]
Hi! I maintain this software as a package for Arch Linux, as it is used to build plugins from it.
GTK2 is now EOL and distributions will start to phase it out of existence.

Is it possible to port this software to use another UI framework instead?
Popular choices for plugins seem to be [pugl](https://gitlab.com/lv2/pugl/), [JUCE](https://github.com/juce-framework/JUCE) and [DPF](https://github.com/DISTRHO/DPF).

GTK and Qt are known to cause trouble with host software and some of the hosts do not allow loading plugins based on these UI frameworks anymore.

**Comment by mfisher31** [comment]
Will be dropping support for all toolkit GUI's in the examples.  Probably will go with pugl + a lightweight GL toolkit like nuklear.

**Comment by mfisher31** [comment]
Looks like toolkit guis were already removed in the `master` branch.

**Comment by dvzrv** [comment]
@mfisher31 can you please cut a new release of lvtk then, so I can drop the gtk2 dependencies?
Dropping this in the current default branch is unfortunately not enough for being able to use this downstream (as we package releases).

**Comment by mfisher31** [comment]
I plan on doing that soon.  I just switched from waf to meson.  You might want to do a test off `master` since the entire build is different now.
